var blogList = [
    {
        "id":1,
        "title":"How I mentally coped in Polytechnic as a shy and reticent person with less-than-ideal conversational skills",
        "publishDate":new Date("04/12/2025").toDateString(),
        "duration":4,
        "htmlContent":`
            <p>As someone who used to face numerous communication difficulties in my youth, it was a huge challenge to navigate through complex social interactions with my peers. Growing up in primary and secondary school, my conversational skills were relatively impaired, which was likely caused by being a late talker at age 4, and the fact that my brain is a little bit different from others <i>(neurodivergent gang lesgoo!)</i>.</p>
                    <p>As a result, I severely lacked the skills required for me to have a smooth conversation with my peers without prompting, coupled with noticeable language delays. Because of these hardships, I have indeed went through numerous painful journeys of misunderstandings, which have ultimately shaped the way I am today. With that, here are some tips I used to improve my conversational journey since the start of my Polytechnic education.</p>
                    <br>
                    <h5><u>1. Join Orientations! 🎊</u></h5>
                    <p>Orientation is one of the best opportunities to not only introduce yourself and meet new people, but also to enjoy fun activities and bond with your peers (if all goes to plan!). However, this did not come easy for me as firstly, I was a very reticent person who typically shy away from most things. On top of that, I faced numerous anxiety attacks because I was not used to meeting so many new people all at once.</p>
                    <p>Despite my internal mental battles, it has eventually helped me to build strong interpersonal connections with my peers in my orientation groups, as we were mostly grouped together in the same class. I am extremely thankful to the camaraderie and understanding of my classmates, who were patient and supportive of my needs.</p>
                    <p>Additionally, I get to meet a wide spectrum of students all across many different backgrounds all across Singapore. If you are going through a tough time during orientation, always remind yourself: you&rsquo;ve already done something brave by stepping out of your comfort zone &mdash; and that&rsquo;s a big win!</p>
                    <br>
                    <h5><u>2. Ask someone you really trust for suggestions on communicating in difficult situations 😊</u></h5>
                    <p>I know this might sound a little bit kiddish, but having someone who can guide you with your conversational skills is essentially crucial, especially because Polytechnic is known for its rigorous group-work assignments.</p>
                    <p>When I was faced with difficulties with working in group projects, I asked my parents for advice on how to communicate better with my groupmates, and it did help out to a certain extent. At first, it felt like trial and error, but with practice and persistence, I gradually learned how to communicate more effectively in team settings.</p>
                    <p>Over time, I managed to communicate effectively with my peers, and I was able to fulfil most of the assignments' requirements, and in a many cases, exceeding them. This led me to getting in maintaining my cumulative GPA of at least 3.9/4 for the first 4 semesters and I am extremely grateful to the teamwork and support of my group members who understood my limitations and accepted me as a functioning groupmate.</p>
                    <br>
                    <h5><u>3. If possible, share your unique story about your own challenges with your classmates in a module! 🗣️</u></h5>
                    <p>This might sound like a challenge as this is quite a step out of your comfort zone, but I'll tell you, it's worth it to a certain extent. I was very blessed and fortunate to have an interdisciplinary communication module (modules that every student across all disciplines in Polytechnic has to fulfil) that allows us to share our unique struggles and challenges we face on our day-to-day lives.</p>
                    <p>For one of the assignments, we had to give a presentation that allowed us to share our life experiences. Naturally, I chose to talk about my daily struggles with communication and social interaction. At first, I was nervous, unsure of how my classmates would respond. But when I finished, I was met with a thunderous round of applause. To top it off, I received a 'Distinction' grade for the module!</p>
                    <p>What made it even more meaningful was that I had been with this same group of classmates for nearly two years. After I shared my story, they became more understanding and empathetic toward the challenges I faced. It helped build stronger bonds and created a more supportive environment, not just for me but for others who might have their own invisible struggles too.</p>
                    <br>
                    <h5><u>Final Thoughts 💭</u></h5>
                    <p>My journey in Polytechnic has been far from easy, especially as someone who started with less-than-ideal conversational skills. But by stepping out of my comfort zone, seeking advice from trusted people, and sharing my story with honesty, I managed to turn these challenges into growth opportunities.</p>
                    <p>If you're like me - shy, anxious, or feeling a bit lost in complex social situations - remember: every small step counts. Progress may feel slow at times, but with persistence and the right support, you'll find your voice in your own time.</p>
                    <p>Keep going. you got this. :) 💪</p>
        `
    },
    {
        "id":1,
        "title":"How joining my hall's running CCA helped me with running!",
        "publishDate":new Date("04/13/2025").toDateString(),
        "duration":3,
        "htmlContent":`
            <h5>How joining a running CCA helped me with running!</h5>
            <p>I have been running as a hobby for about 6 years, but my progress plateaued - my pace stayed roughly the same over the years, and my heart rate remained relatively high. However, things have changed when I stepped outside my comfort zone to join my hall&#039;s Road Relay CCA, despite not knowing anyone in my hall before this (as I didn&#039;t join my hall&#039;s orientation due to National Service).</p>
            <p>I was hoping they had a running CCA. And there was no surprise that they did, when one of the members approached me and asked if I was interested in running. As a person who typically does long-distance runs (≥5 km per run), I was open to their training regimen, which focused on speed workouts and interval training, usually covering distances in the middle range (~1.6–5 km). I didn&#039;t hesitate - I happily signed up for the CCA.</p>
            <p>Despite not having a lot of prior experience with training for running, I was surprisingly competent enough to keep up with their training regimen. As the training regimen mainly consisted of speed workouts and interval training, it was undoubtedly not easy for me to feel at ease during my runs. It was nothing like how I felt during my typical long runs - usually calm with strong hints of exhaustion 😪. Every time I suffered during the process, the stronger I became, and surprisingly, I felt a rush of dopamine right after finishing my last set of fast runs. Even though I was busy adjusting to university life, making time for training kept me grounded and motivated. Additionally, I totally didn&#039;t expect to break several personal bests during their training - 9:06 for 2.4 km and 21:12 for 5 km.</p>
            <p>Because of my competence, I was one of the few people selected to take part in this year&#039;s Inter-Hall Olympiad Games for Road Relay, which felt like a huge milestone in my running journey. Being part of the team not only pushed me to improve physically but also gave me a sense of belonging in my hall community. I&#039;m excited to continue this journey and see where it takes me next! As the competition was held late in the morning, the weather was much worse than ideal - the sun was glaring down on the track, and the temperature felt blazing like the floor was lava. Despite this, I was determined to try my best to represent my hall proudly. However, I felt a wave of anxiousness sweep inside of me as it was my very first time in my life that I was representing my school in some way. Additionally, I felt like my performance was much worse than I expected - 10:30 for 2.5 km (I was expecting to run under 10 minutes), because the sun was strong enough to penetrate through my shoes. Despite this, I am grateful that my team managed to clinch 1st Runner-Up, which is also the very first time my hall has received a medal for Road Relay!</p>
            <p>Looking back, I felt like joining a running CCA was one of the best decisions I made to improve my running stamina - I was surrounded by people who shared the same experience as me and were willing to experience of hardships of training along together. The fact that I was surrounded by people who not only had similar interests, but they also motivated me to reach greater levels. Therefore, I highly recommend that you step outside your comfort zone to join a club that motivates you to become better at something you love to do.</p>
        `
    }
];