var projInfo = [{
    "proj_id": 1,
    "title": "Minecraft Fill Generator!",
    "title_jp": "マインクラフトフィル生成器！",
    "title_zh": "Minecraft （我的世界）填充生成器！",
    "brief_description_jp": "描いたものから3Dモデルを生成！",
    "brief_description_zh": "根据你的绘图生成 3D 模型！",
    "brief_description": "Generate a 3d model of what you have drawn!",
    "image_location": "./img/coding/coding_proj1.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Minecraft-Fill-Generator/index.html",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
}, {
    "proj_id": 2,
    "title": "Minecraft Like Replica!",
    "title_jp": "マインクラフト風レプリカ！",
    "title_zh": "Minecraft （我的世界）风格复制品！",
    "brief_description_jp": "プレイヤーが動けるボクセルシミュレーション！",
    "brief_description_zh": "带有玩家移动功能的体素模拟！",
    "brief_description": "Voxel simulation with player movement!",
    "image_location": "./img/coding/coding_proj2.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Minecraft-Like-Replica/public/",
    "in_development": 2,
    "detailed_description": "My first time attempting player controls and rendering Minecraft-like blocks in Three.js!",
    "is_mini_project": 0
}, {
    "proj_id": 3,
    "title": "Video To Text!",
    "title_jp": "ビデオからテキスト！",
    "title_zh": "视频转文字！",
    "brief_description_jp": "ビデオを再生して、下のテキストの魔法を見よう！",
    "brief_description_zh": "播放视频并查看下面的文字魔法！",
    "brief_description": "Play a video and see the magic from the text below!",
    "image_location": "./img/coding/coding_proj3.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Video-To-Text/public/",
    "in_development": 0,
    "detailed_description": "",
    "is_mini_project": 0
}, {
    "proj_id": 4,
    "title": "2D Spleef!",
    "title_jp": "2Dスプリーフ！",
    "title_zh": "2D淘汰游戏！",
    "brief_description": "2D version of Spleef! Made using Java.",
    "brief_description_jp": "走ると足元のブロックが消える、Java製の2Dスプリーフゲーム！",
    "brief_description_zh": "用Java制作的2D淘汰游戏，玩家踩过的方块会消失！",
    "image_location": "./img/coding/coding_proj4.png",
    "link": "https://github.com/pixelhypercube/Side-Projects/tree/main/2d-Spleef",
    "in_development": 0,
    "detailed_description": "A two-dimensional spleef game made using Java!",
    "is_mini_project": 0
}, {
    "proj_id": 5,
    "title": "Visual Matrix Operators!",
    "title_jp": "ビジュアル行列演算！",
    "title_zh": "可视化矩阵运算器！",
    "brief_description_jp": "加算・減算・乗算などの行列演算を視覚化！",
    "brief_description_zh": "帮助可视化加法、减法和乘法等矩阵运算！",
    "brief_description": "Helps to visualize matrix operations like addition, subtraction and multiplication!",
    "image_location": "./img/coding/coding_proj6.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Visual-Matrix-Operators/",
    "in_development": 3,
    "detailed_description": null,
    "is_mini_project": 1
}, {
    "proj_id": 6,
    "title": "Console Spaceship Battle!",
    "title_jp": "コンソール宇宙船バトル！",
    "title_zh": "控制台太空船大战！",
    "brief_description_jp": "Pythonで作成された宇宙船バトルゲーム！",
    "brief_description_zh": "使用 Python 制作的太空船对战游戏！",
    "brief_description": "A spaceship battle game in a console! Made using Python",
    "image_location": "./img/coding/coding_proj7.png",
    "link": "https://github.com/pixelhypercube/Side-Projects/tree/main/Console-Spaceship-Battle",
    "in_development": 0,
    "detailed_description": "Use the WASD keys to move and the spacebar to shoot! Attack and destroy as many spaceships as you can!",
    "is_mini_project": 0
}, {
    "proj_id": 7,
    "title": "PHC Minigolf",
    "title_jp": "PHCミニゴルフ",
    "title_zh": "PHC 迷你高尔夫",
    "brief_description_jp": "Python（pygame）で作ったミニゴルフゲーム！",
    "brief_description_zh": "用 Python（pygame）制作的迷你高尔夫游戏！",
    "brief_description": "A minigolf game made using python (pygame!)",
    "image_location": "./img/coding/coding_proj8.png",
    "link": "https://github.com/pixelhypercube/Side-Projects/tree/main/PHC-Minigolf",
    "in_development": 0,
    "detailed_description": "",
    "is_mini_project": 0
}, {
    "proj_id": 8,
    "title": "Pi Approximation",
    "title_jp": "円周率近似",
    "title_zh": "π 值近似模拟器",
    "brief_description_jp": "円周率（π）を推定する方法をシミュレーション！",
    "brief_description_zh": "模拟估算数学常数 π 的方法之一。",
    "brief_description": "Simulates one of the methods of estimating the mathematical constant pi (π).",
    "image_location": "./img/coding/coding_proj9.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Pi-Approximation/index.html",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
}, {
    "proj_id": 9,
    "title": "Coin Dozer Replica!",
    "title_jp": "コインプッシャーレプリカ！",
    "title_zh": "推币机仿制品！",
    "brief_description_jp": "matter.jsとp5.jsで作った2Dコインプッシャー！",
    "brief_description_zh": "用 matter.js 和 p5.js 制作的 2D 推币机！",
    "brief_description": "A mini 2D online Coin Dozer made using matter.js and p5.js!",
    "image_location": "./img/coding/coding_proj10.png",
    "link": "https://pixelhypercube.github.io/Side-Projects/Coin-Dozer-Replica/index.html",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
}, {
    "proj_id": 10,
    "title": "Telegram Tic Tac Toe Bot",
    "title_jp": "テレグラム三目並べボット",
    "title_zh": "Telegram 井字棋机器人",
    "brief_description_jp": "テレグラムで三目並べが遊べるボット！",
    "brief_description_zh": "一个可以在 Telegram 上玩的井字棋机器人！",
    "brief_description": "A telegram bot that let's you play tic tac toe!",
    "image_location": "./img/coding/coding_proj11.png",
    "link": "https://github.com/pixelhypercube/Telegram-Tic-Tac-Toe",
    "in_development": 1,
    "detailed_description": null,
    "is_mini_project": 0
}, {
    "proj_id": 11,
    "title": "Loves Me... ?",
    "title_jp": "ラブ・ミー...?",
    "title_zh": "爱我...？",
    "brief_description_jp": "スーパーマリオ64DSのミニゲームを再現！",
    "brief_description_zh": "重制自《超级马里奥64 DS》的小游戏！",
    "brief_description": "A remake of a minigame from Super Mario 64 DS!",
    "image_location": "./img/coding/coding_proj12.png",
    "link": "https://pixelhypercube.github.io/Loves-Me-Replica",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
}, {
    "proj_id": 12,
    "title": "pySquidGame",
    "title_jp": "pyイカゲーム",
    "title_zh": "py鱿鱼游戏",
    "brief_description": "A playable pygame application based on Netflix's 'Squid Game'!",
    "brief_description_jp": "Netflixの「イカゲーム」に基づいたプレイ可能なpygameアプリ！",
    "brief_description_zh": "基于 Netflix《鱿鱼游戏》的可玩 pygame 应用！",
    "image_location": "./img/coding/coding_proj13.png",
    "link": "https://github.com/pixelhypercube/pySquidGame",
    "in_development": 3,
    "detailed_description": null,
    "is_mini_project": 0
},{
    "proj_id": 13,
    "title": "RActive",
    "title_jp": "RActive：RA支援アプリ",
    "title_zh": "RActive：类风湿性关节炎管理应用",
    "brief_description": "A Figma prototype to assist individuals with rheumatoid arthritis (RA) in managing daily activities. Created for CC0005 – Healthy Living and Wellbeing at NTU.",
    "brief_description_jp": "関節リウマチ（RA）患者の日常管理を支援するFigmaプロトタイプ。NTUの「CC0005：健康的な生活とウェルビーイング」科目のために作成。",
    "brief_description_zh": "一个帮助类风湿性关节炎（RA）患者管理日常生活的 Figma 原型。为 NTU 的 CC0005 健康生活与福祉课程设计。",
    "image_location": "./img/coding/coding_proj14.png",
    "link": "https://www.figma.com/design/hiWbnOFAR7KPcpiU9cQMwe/CC0005-App?node-id=210-240&t=F7NivajSw7bWbxKb-0",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
},{
    "proj_id": 14,
    "title": "CPP Physics",
    "brief_description": "A mini C++ program that simulates physics between objects!",
    "title_jp": "CPP物理シミュレーション",
    "title_zh": "CPP 物理模拟器",
    "brief_description_jp": "物体間の物理をシミュレーションする小さなC++プログラム！",
    "brief_description_zh": "一个模拟物体间物理互动的小型 C++ 程序！",
    "image_location": "./img/coding/coding_proj15.png",
    "link": "https://github.com/pixelhypercube/Side-Projects/tree/main/CPP-Physics",
    "in_development": 0,
    "detailed_description": null,
    "is_mini_project": 0
}];

projInfo.reverse();
